name: Build python-ldap wheels for Windows

on:
  workflow_dispatch:

env:
  OPENSSL_VER: openssl-1.1.1w
  OPENLDAP_VER: openldap-2.4.59
  PYTHONLDAP_VER: python-ldap-3.4.4
  CIBW_TEST_COMMAND: python -c"import ldap;print(ldap.__version__)"
  CIBW_SKIP: "pp* cp36*"
  MSBUILDTREATHIGHERTOOLSVERSIONASCURRENT: 1

jobs:
  build_amd64:
    name: Build AMD64 wheels
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]
    env:
      VS_PLATFORM: x64
      OPENSSL_CONFIG: VC-WIN64A-masm
    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
      - run: build_openssl.cmd
        shell: cmd
      - run: build_openldap.cmd
        shell: cmd
      - run: build_python-ldap.cmd
        shell: cmd
      - uses: pypa/cibuildwheel@v2.16.2
        env:
          CIBW_ARCHS_WINDOWS: AMD64
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
  build_x86:
    name: Build x86 wheels
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]
    env:
      VS_PLATFORM: Win32
      OPENSSL_CONFIG: VC-WIN32
    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x86
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64_x86
      - uses: ilammy/setup-nasm@v1
      - run: build_openssl.cmd
        shell: cmd
      - run: build_openldap.cmd
        shell: cmd
      - run: build_python-ldap.cmd
        shell: cmd
      - uses: pypa/cibuildwheel@v2.16.2
        env:
          CIBW_ARCHS_WINDOWS: x86
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
  # ARM64 wheel is broken
  # build_arm64:
  #  name: Build ARM64 wheels
  #  runs-on: ${{ matrix.os }}
  #  strategy:
  #    matrix:
  #      os: [windows-2022]
  #  env:
  #    VS_PLATFORM: ARM64
  #    OPENSSL_CONFIG: VC-WIN64-ARM
  #  steps:
  #    - uses: actions/checkout@v4
  #    - uses: microsoft/setup-msbuild@v1.1
  #      with:
  #        msbuild-architecture: arm64
  #    - uses: ilammy/msvc-dev-cmd@v1
  #      with:
  #        arch: amd64_arm64
  #    - run: build.cmd
  #      shell: cmd
  #    - uses: pypa/cibuildwheel@v2.16.2
  #      env:
  #        CIBW_SKIP: "pp* cp36* cp37* cp38* cp39* cp310*"
  #        CIBW_ARCHS_WINDOWS: ARM64
  #    - uses: actions/upload-artifact@v3
  #      with:
  #        path: ./wheelhouse/*.whl